<?php
require_once "model/Note.php";

class TextNote extends Note {

    private ?string $content;

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function __construct(int $id, ?string $content) {
        parent::__construct($id, " ", 0, new DateTime(), null, 0, 0, 0);
        $this->content = $content;
    }


    public static function validate(string $title): string
    {
        return parent::validate($title); // TODO: Change the autogenerated stub
    }









//        if($this->getId()){
//            self::execute("UPDATE notes SET content = :content  WHERE id = :id",
//        ["id" => $this->getId(), "content" => $this->content]);
//
//
//        }else{
//            self::execute("INSERT INTO notes(content) VALUES (:content)",
//            ["content" => $this->content]);
//
//            $this->setId(self::lastInsertId());
//        }
//        return $this;
//    }






    public function persist(): TextNote | array {
        var_dump($this->getWeight());
        $currentDateTime = new DateTime('now');
        // Vérifier si la note existe déjà dans la base de données
        if (!self::get_textnote_by_id($this->getId())) {
            // Si la note n'existe pas, l'insérer dans la base de données
            $lastWeight = parent::getLastWeightNote();

            // Insérer une nouvelle note dans 'notes'
            self::execute("INSERT INTO notes (title, owner, created_at, edited_at, pinned, archived, weight)
                       VALUES (:title, :owner, :createdAt, :editedAt, :pinned, :archived, :weight)",
                [
                    'title' => $this->getTitleNote(),
                    'owner' => $this->getOwner(),
                    'createdAt' => $this->getDateTime()->format('Y-m-d H:i:s'),
                    'editedAt' => $this->getDateTimeEdit() ? $this->getDateTimeEdit()->format('Y-m-d H:i:s') : null,
                    'pinned' => $this->getPinned(),
                    'archived' => $this->getArchived(),
                    'weight' => $lastWeight + 1
                ]);
            $this->setId(self::lastInsertId());

            // Insérer dans 'text_notes'
            self::execute(
                "INSERT INTO text_notes (id, content) VALUES (:id, :content)",
                ['id' => $this->getId(), 'content' => $this->content]
            );
        } else {
            // Si la note existe, mettre à jour les données dans la base de données

            // Mettre à jour la note existante dans 'notes'
            self::execute("UPDATE notes SET title = :title, created_at = :createdAt, 
                       edited_at = :editedAt, pinned = :pinned, archived = :archived, weight = :weight 
                       WHERE id = :id",
                [
                    'id' => $this->getId(),
                    'title' => $this->getTitle(),
                    'createdAt' => $this->getDateTime()->format('Y-m-d H:i:s'),
                    'editedAt' => $this->getDateTimeEdit() ? $this->getDateTimeEdit()->format('Y-m-d H:i:s') : null,
                    'pinned' => $this->getPinned(),
                    'archived' => $this->getArchived(),
                    'weight' => $this->getWeight()
                ]);

            // Mettre à jour le contenu dans 'text_notes'
            self::execute(
                "UPDATE text_notes SET content = :content WHERE id = :id",
                ['id' => $this->getId(), 'content' => $this->content]
            );
        }

        return $this;
    }





    public function delete(): void
{
    self::execute("DELETE FROM text_notes WHERE id = :id", ["id" => $this->getId()]);
    parent::delete(); // TODO: Change the autogenerated stub
}





    public function setContent(?string $content): void
    {
        $this->content = $content;
    }

    public function getType(): NoteType
    {
        return  NoteType::TextNote;
    }




//    public static function geteditDateTime(int $id): string|null{
//        $query = self::execute("SELECT notes.edited_at FROM notes WHERE notes.id = :id", ["id" => $id]);
//        $data = $query->fetchAll();
//        $results = "";
//        foreach ($data as $row){
//            $results = $row['edited_at'];
//        }
//        return $results;
//    }
//
//

    public function getTitle(): string
    {
        $query = self::execute("SELECT notes.title from notes WHERE notes.id = :id", ["id" => $this->getId()]);
        $data = $query->fetchAll();
        $results = "";
        foreach ($data as $row){
            $results = $row['title'];
        }
        return $results;
    }




}